/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_foursquare_rec_lib_image_CaffeFeatureExtractor */

#ifndef _Included_com_foursquare_rec_lib_image_CaffeFeatureExtractor
#define _Included_com_foursquare_rec_lib_image_CaffeFeatureExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_foursquare_rec_lib_image_CaffeFeatureExtractor
 * Method:    startFeatureExtraction
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_foursquare_rec_lib_image_CaffeFeatureExtractor_startFeatureExtraction
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_foursquare_rec_lib_image_CaffeFeatureExtractor
 * Method:    runFeatureExtraction
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_foursquare_rec_lib_image_CaffeFeatureExtractor_runFeatureExtraction
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_foursquare_rec_lib_image_CaffeFeatureExtractor
 * Method:    processBatch
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foursquare_rec_lib_image_CaffeFeatureExtractor_processBatch
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_foursquare_rec_lib_image_CaffeFeatureExtractor
 * Method:    stopFeatureExtraction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_foursquare_rec_lib_image_CaffeFeatureExtractor_stopFeatureExtraction
  (JNIEnv *, jobject);

/*
 * Class:     com_foursquare_rec_lib_image_CaffeFeatureExtractor
 * Method:    _resizeRawImage
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foursquare_rec_lib_image_CaffeFeatureExtractor__1resizeRawImage
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
