/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_foursquare_caffe_jMRFeatureExtraction */

#ifndef _Included_com_foursquare_caffe_jMRFeatureExtraction
#define _Included_com_foursquare_caffe_jMRFeatureExtraction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_foursquare_caffe_jMRFeatureExtraction
 * Method:    startFeatureExtraction
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_foursquare_caffe_jMRFeatureExtraction_startFeatureExtraction
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_foursquare_caffe_jMRFeatureExtraction
 * Method:    stopFeatureExtraction
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_com_foursquare_caffe_jMRFeatureExtraction_stopFeatureExtraction
  (JNIEnv *, jobject);

/*
 * Class:     com_foursquare_caffe_jMRFeatureExtraction
 * Method:    getInputPipePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foursquare_caffe_jMRFeatureExtraction_getInputPipePath
  (JNIEnv *, jobject);

/*
 * Class:     com_foursquare_caffe_jMRFeatureExtraction
 * Method:    getOutputPipePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foursquare_caffe_jMRFeatureExtraction_getOutputPipePath
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
